services:
  cue-splitter:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: cue-splitter
    ports:
    - 80:80
    - 5000:5000
    environment:
      - CUE_GUNICORN_WORKERS=4
      - CUE_API_TIMEOUT=300
    volumes:
      - ./cue-splitter:/cue-splitter
    networks:
      - cue-splitter
    restart: unless-stopped

networks:
  cue-splitter:
    name: cue-splitter

