services:
  proxy:
    image: cue-splitter/proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      - app_nat
    restart: always
    
  backend:
    image: cue-splitter/splitter
    container_name: splitter
    ports:
      - "5000:5000"
    networks:
      - app_nat
    restart: always
    volumes:
      - /tmp/splitter:/tmp/splitter
networks:
  app_nat:
    driver: bridge

